# Generated by Django 3.2.5 on 2022-10-22 20:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_estado', models.CharField(error_messages={'unique': 'O Estado em questão já foi registrado.'}, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('unidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_unidade', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone_unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao_unidade', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.ForeignKey(db_column='fk_estado_id', on_delete=django.db.models.deletion.CASCADE, related_name='unidade_estado_fk', to='adoteme.estado')),
                ('responsavel', models.ForeignKey(db_column='fk_responsavel_id', on_delete=django.db.models.deletion.CASCADE, related_name='unidade_responsavel_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_animal', models.CharField(blank=True, max_length=200, null=True)),
                ('unidade', models.ForeignKey(db_column='fk_unidade_id', on_delete=django.db.models.deletion.CASCADE, related_name='animal_unidade_fk', to='adoteme.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='ListaAdocao',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('adotante', models.ForeignKey(db_column='fk_responsavel_id', on_delete=django.db.models.deletion.CASCADE, related_name='lista_responsavel_fk', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(db_column='fk_animal_id', on_delete=django.db.models.deletion.CASCADE, related_name='lista_animal_fk', to='adoteme.animal')),
            ],
            options={
                'unique_together': {('animal', 'adotante')},
            },
        ),
    ]
