# Generated by Django 4.1 on 2022-10-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoteme', '0002_alter_unidade_descricao_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='descricao_animal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
