# Generated by Django 3.2.5 on 2022-11-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoteme', '0003_alter_animal_descricao_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='raca_animal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
