# Generated by Django 3.2.5 on 2022-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoteme', '0005_auto_20221102_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listaadocao',
            old_name='adotado',
            new_name='adotante_adotou',
        ),
        migrations.AddField(
            model_name='animal',
            name='adotado',
            field=models.BooleanField(default=False),
        ),
    ]
