# Generated by Django 3.2.5 on 2022-11-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoteme', '0006_auto_20221102_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaadocao',
            name='justificativa_viagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaadocao',
            name='motivo_adocao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaadocao',
            name='posse_animal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
